package com.tealium.remotecommands.appsflyer

interface AppsFlyerCommand {
    fun initialize(devKey: String? = null, configSettings: Map<String, Any>? = null)
    fun trackLocation(latitude: Double, longitude: Double)
    fun setHost(host: String, hostPrefix: String? = "")
    fun trackEvent(eventType: String, eventParameters: Map<String, Any>? = null)
    fun setUserEmails(emails: List<String>, cryptType: Int = 0)
    fun setCurrencyCode(currency: String)
    fun setCustomerId(id: String)
    fun disableDeviceTracking(disable: Boolean)
    fun resolveDeepLinkUrls(links: List<String>)
    fun stopTracking(isTrackingStopped: Boolean)
    fun anonymizeUser(shouldAnonymize: Boolean)
    fun logAdRevenue(monetizationNetwork: String, mediationNetwork: String, revenue: Double, currency: String, additionalParams: Map<String, Any>? = null)
    fun setDMAConsent(gdprApplies: Boolean, consentForDataUsage: Boolean, consentForAdsPersonalization: Boolean, consentForAdStorage: Boolean)
    fun setPhoneNumber(phoneNumber: String)
    fun addPushNotificationDeepLinkPath(path: List<String>)
    fun validateAndLogPurchase(purchaseType: String, purchaseToken: String, productId: String, price: String, currency: String, additionalParams: Map<String, String>? = null)
    fun setSharingFilterForPartners(partners: List<String>)
    fun appendCustomData(customData: Map<String, Any>)
    fun setDeviceLanguage(language: String)
    fun setPartnerData(partnerId: String, partnerData: Map<String, Any>)
    fun appendParametersToDeepLinkUrl(urlContains: String, parameters: Map<String, String>)
    fun setIsUpdate(isUpdate: Boolean)
    fun setOutOfStore(outOfStore: String)
    fun setPreinstallAttribution(mediaSource: String, campaign: String, siteId: String? = null)
    fun setAndroidIdData(androidId: String)
    fun setImeiData(imei: String)
    fun setOaidData(oaid: String)
}